kind: pipeline
type: docker
name: default

steps:
-   name: compress_and_zip
    image: node:alpine
    commands:
    - npm install uglify-js -g
    - for i in *.js; do uglifyjs -c -m -o $i $i; done
    - apk add zip
    - zip Boiler-AutoLogin.zip manifest.json *.html *.js
    when:
        event: tag

-   name: gitea_release
    image: plugins/gitea-release
    settings:
        api_key:
            from_secret: gitea_api_key
        base_url: https://gitea.dennx.com
        files:
            - Boiler-AutoLogin.zip

trigger:
  event: tag